/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/model/Daven_v3.2.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene } = useGLTF('/Daven_v3.2.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials, animations } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" scale={0.01}>
          <primitive object={nodes.CC_Base_BoneRoot} />
          <group name="Male_Body">
            <skinnedMesh name="Male_Bushy" geometry={nodes.Male_Bushy.geometry} material={materials.Male_Bushy_Transparency} skeleton={nodes.Male_Bushy.skeleton} morphTargetDictionary={nodes.Male_Bushy.morphTargetDictionary} morphTargetInfluences={nodes.Male_Bushy.morphTargetInfluences} />
            <skinnedMesh name="Male_Bushy_1" geometry={nodes.Male_Bushy_1.geometry} material={materials.Male_Bushy_Base_Transparency} skeleton={nodes.Male_Bushy_1.skeleton} morphTargetDictionary={nodes.Male_Bushy_1.morphTargetDictionary} morphTargetInfluences={nodes.Male_Bushy_1.morphTargetInfluences} />
            <skinnedMesh name="Male_Bushy_2" geometry={nodes.Male_Bushy_2.geometry} material={materials.Std_Skin_Head} skeleton={nodes.Male_Bushy_2.skeleton} morphTargetDictionary={nodes.Male_Bushy_2.morphTargetDictionary} morphTargetInfluences={nodes.Male_Bushy_2.morphTargetInfluences} />
            <skinnedMesh name="Male_Bushy_3" geometry={nodes.Male_Bushy_3.geometry} material={materials.Std_Skin_Body} skeleton={nodes.Male_Bushy_3.skeleton} morphTargetDictionary={nodes.Male_Bushy_3.morphTargetDictionary} morphTargetInfluences={nodes.Male_Bushy_3.morphTargetInfluences} />
            <skinnedMesh name="Male_Bushy_4" geometry={nodes.Male_Bushy_4.geometry} material={materials.Std_Skin_Arm} skeleton={nodes.Male_Bushy_4.skeleton} morphTargetDictionary={nodes.Male_Bushy_4.morphTargetDictionary} morphTargetInfluences={nodes.Male_Bushy_4.morphTargetInfluences} />
            <skinnedMesh name="Male_Bushy_5" geometry={nodes.Male_Bushy_5.geometry} material={materials.Std_Skin_Leg} skeleton={nodes.Male_Bushy_5.skeleton} morphTargetDictionary={nodes.Male_Bushy_5.morphTargetDictionary} morphTargetInfluences={nodes.Male_Bushy_5.morphTargetInfluences} />
            <skinnedMesh name="Male_Bushy_6" geometry={nodes.Male_Bushy_6.geometry} material={materials.Std_Nails} skeleton={nodes.Male_Bushy_6.skeleton} morphTargetDictionary={nodes.Male_Bushy_6.morphTargetDictionary} morphTargetInfluences={nodes.Male_Bushy_6.morphTargetInfluences} />
            <skinnedMesh name="Male_Bushy_7" geometry={nodes.Male_Bushy_7.geometry} material={materials.Std_Eyelash} skeleton={nodes.Male_Bushy_7.skeleton} morphTargetDictionary={nodes.Male_Bushy_7.morphTargetDictionary} morphTargetInfluences={nodes.Male_Bushy_7.morphTargetInfluences} />
            <skinnedMesh name="Male_Bushy_8" geometry={nodes.Male_Bushy_8.geometry} material={materials.Std_Tearline_R} skeleton={nodes.Male_Bushy_8.skeleton} morphTargetDictionary={nodes.Male_Bushy_8.morphTargetDictionary} morphTargetInfluences={nodes.Male_Bushy_8.morphTargetInfluences} />
            <skinnedMesh name="Male_Bushy_9" geometry={nodes.Male_Bushy_9.geometry} material={materials.Std_Tearline_L} skeleton={nodes.Male_Bushy_9.skeleton} morphTargetDictionary={nodes.Male_Bushy_9.morphTargetDictionary} morphTargetInfluences={nodes.Male_Bushy_9.morphTargetInfluences} />
            <skinnedMesh name="Male_Bushy_10" geometry={nodes.Male_Bushy_10.geometry} material={materials.Std_Upper_Teeth} skeleton={nodes.Male_Bushy_10.skeleton} morphTargetDictionary={nodes.Male_Bushy_10.morphTargetDictionary} morphTargetInfluences={nodes.Male_Bushy_10.morphTargetInfluences} />
            <skinnedMesh name="Male_Bushy_11" geometry={nodes.Male_Bushy_11.geometry} material={materials.Std_Lower_Teeth} skeleton={nodes.Male_Bushy_11.skeleton} morphTargetDictionary={nodes.Male_Bushy_11.morphTargetDictionary} morphTargetInfluences={nodes.Male_Bushy_11.morphTargetInfluences} />
            <skinnedMesh name="Male_Bushy_12" geometry={nodes.Male_Bushy_12.geometry} material={materials.Std_Eye_Occlusion_R} skeleton={nodes.Male_Bushy_12.skeleton} morphTargetDictionary={nodes.Male_Bushy_12.morphTargetDictionary} morphTargetInfluences={nodes.Male_Bushy_12.morphTargetInfluences} />
            <skinnedMesh name="Male_Bushy_13" geometry={nodes.Male_Bushy_13.geometry} material={materials.Std_Eye_Occlusion_L} skeleton={nodes.Male_Bushy_13.skeleton} morphTargetDictionary={nodes.Male_Bushy_13.morphTargetDictionary} morphTargetInfluences={nodes.Male_Bushy_13.morphTargetInfluences} />
            <skinnedMesh name="Male_Bushy_14" geometry={nodes.Male_Bushy_14.geometry} material={materials.Std_Tongue} skeleton={nodes.Male_Bushy_14.skeleton} morphTargetDictionary={nodes.Male_Bushy_14.morphTargetDictionary} morphTargetInfluences={nodes.Male_Bushy_14.morphTargetInfluences} />
            <skinnedMesh name="Male_Bushy_15" geometry={nodes.Male_Bushy_15.geometry} material={materials.Std_Eye_R} skeleton={nodes.Male_Bushy_15.skeleton} morphTargetDictionary={nodes.Male_Bushy_15.morphTargetDictionary} morphTargetInfluences={nodes.Male_Bushy_15.morphTargetInfluences} />
            <skinnedMesh name="Male_Bushy_16" geometry={nodes.Male_Bushy_16.geometry} material={materials.Std_Cornea_R} skeleton={nodes.Male_Bushy_16.skeleton} morphTargetDictionary={nodes.Male_Bushy_16.morphTargetDictionary} morphTargetInfluences={nodes.Male_Bushy_16.morphTargetInfluences} />
            <skinnedMesh name="Male_Bushy_17" geometry={nodes.Male_Bushy_17.geometry} material={materials.Std_Eye_L} skeleton={nodes.Male_Bushy_17.skeleton} morphTargetDictionary={nodes.Male_Bushy_17.morphTargetDictionary} morphTargetInfluences={nodes.Male_Bushy_17.morphTargetInfluences} />
            <skinnedMesh name="Male_Bushy_18" geometry={nodes.Male_Bushy_18.geometry} material={materials.Std_Cornea_L} skeleton={nodes.Male_Bushy_18.skeleton} morphTargetDictionary={nodes.Male_Bushy_18.morphTargetDictionary} morphTargetInfluences={nodes.Male_Bushy_18.morphTargetInfluences} />
          </group>
        </group>
        <mesh name="Boots" geometry={nodes.Boots.geometry} material={materials['Boots.001']} scale={0.01} />
        <group name="Layered_sweater" scale={0.01}>
          <mesh name="Layered_sweater_1" geometry={nodes.Layered_sweater_1.geometry} material={materials.Layered_sweater} />
          <mesh name="Layered_sweater_2" geometry={nodes.Layered_sweater_2.geometry} material={materials['Material.001']} />
        </group>
        <mesh name="Slim_Jeans" geometry={nodes.Slim_Jeans.geometry} material={materials['Slim_Jeans.001']} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/Daven_v3.2.glb')
