/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/model2/Daven_v3.2.gltf -o src/components/Avatar2.tsx -r public 
*/

import * as THREE from 'three';
import React from 'react';
import { useGraph } from '@react-three/fiber';
import { useGLTF, PerspectiveCamera } from '@react-three/drei';
import { GLTF, SkeletonUtils } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Male_Bushy: THREE.SkinnedMesh;
    Male_Bushy_1: THREE.SkinnedMesh;
    Male_Bushy_2: THREE.SkinnedMesh;
    Male_Bushy_3: THREE.SkinnedMesh;
    Male_Bushy_4: THREE.SkinnedMesh;
    Male_Bushy_5: THREE.SkinnedMesh;
    Male_Bushy_6: THREE.SkinnedMesh;
    Male_Bushy_7: THREE.SkinnedMesh;
    Male_Bushy_8: THREE.SkinnedMesh;
    Male_Bushy_9: THREE.SkinnedMesh;
    Male_Bushy_10: THREE.SkinnedMesh;
    Male_Bushy_11: THREE.SkinnedMesh;
    Male_Bushy_12: THREE.SkinnedMesh;
    Male_Bushy_13: THREE.SkinnedMesh;
    Male_Bushy_14: THREE.SkinnedMesh;
    Male_Bushy_15: THREE.SkinnedMesh;
    Male_Bushy_16: THREE.SkinnedMesh;
    Male_Bushy_17: THREE.SkinnedMesh;
    Male_Bushy_18: THREE.SkinnedMesh;
    Side_part_wavy_1: THREE.SkinnedMesh;
    Side_part_wavy_2: THREE.SkinnedMesh;
    Lighting_Setup_Generator: THREE.Mesh;
    Boots: THREE.Mesh;
    Layered_sweater_1: THREE.Mesh;
    Layered_sweater_2: THREE.Mesh;
    Slim_Jeans: THREE.Mesh;
    CC_Base_BoneRoot: THREE.Bone;
    CC_Base_BoneRoot_1: THREE.Bone;
  };
  materials: {
    Male_Bushy_Transparency: THREE.MeshStandardMaterial;
    Male_Bushy_Base_Transparency: THREE.MeshStandardMaterial;
    Std_Skin_Head: THREE.MeshStandardMaterial;
    Std_Skin_Body: THREE.MeshStandardMaterial;
    Std_Skin_Arm: THREE.MeshStandardMaterial;
    Std_Skin_Leg: THREE.MeshStandardMaterial;
    Std_Nails: THREE.MeshStandardMaterial;
    Std_Eyelash: THREE.MeshStandardMaterial;
    Std_Tearline_R: THREE.MeshStandardMaterial;
    Std_Tearline_L: THREE.MeshStandardMaterial;
    Std_Upper_Teeth: THREE.MeshStandardMaterial;
    Std_Lower_Teeth: THREE.MeshStandardMaterial;
    Std_Eye_Occlusion_R: THREE.MeshStandardMaterial;
    Std_Eye_Occlusion_L: THREE.MeshStandardMaterial;
    Std_Tongue: THREE.MeshStandardMaterial;
    Std_Eye_R: THREE.MeshStandardMaterial;
    Std_Cornea_R: THREE.MeshStandardMaterial;
    Std_Eye_L: THREE.MeshStandardMaterial;
    Std_Cornea_L: THREE.MeshStandardMaterial;
    Scalp_Transparency: THREE.MeshStandardMaterial;
    Hair_Transparency: THREE.MeshStandardMaterial;
    ['Boots.001']: THREE.MeshStandardMaterial;
    Layered_sweater: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
    ['Slim_Jeans.001']: THREE.MeshStandardMaterial;
  };
  //animations: GLTFAction[]
};

export function Avatar2(props: JSX.IntrinsicElements['group']) {
  const { scene } = useGLTF('/model2/Daven_v3.2.gltf');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <primitive object={nodes.CC_Base_BoneRoot} />
        <skinnedMesh
          name="Male_Bushy"
          geometry={nodes.Male_Bushy.geometry}
          material={materials.Male_Bushy_Transparency}
          skeleton={nodes.Male_Bushy.skeleton}
          morphTargetDictionary={nodes.Male_Bushy.morphTargetDictionary}
          morphTargetInfluences={nodes.Male_Bushy.morphTargetInfluences}
        />
        <skinnedMesh
          name="Male_Bushy_1"
          geometry={nodes.Male_Bushy_1.geometry}
          material={materials.Male_Bushy_Base_Transparency}
          skeleton={nodes.Male_Bushy_1.skeleton}
          morphTargetDictionary={nodes.Male_Bushy_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Male_Bushy_1.morphTargetInfluences}
        />
        <skinnedMesh
          name="Male_Bushy_2"
          geometry={nodes.Male_Bushy_2.geometry}
          material={materials.Std_Skin_Head}
          skeleton={nodes.Male_Bushy_2.skeleton}
          morphTargetDictionary={nodes.Male_Bushy_2.morphTargetDictionary}
          morphTargetInfluences={nodes.Male_Bushy_2.morphTargetInfluences}
        />
        <skinnedMesh
          name="Male_Bushy_3"
          geometry={nodes.Male_Bushy_3.geometry}
          material={materials.Std_Skin_Body}
          skeleton={nodes.Male_Bushy_3.skeleton}
          morphTargetDictionary={nodes.Male_Bushy_3.morphTargetDictionary}
          morphTargetInfluences={nodes.Male_Bushy_3.morphTargetInfluences}
        />
        <skinnedMesh
          name="Male_Bushy_4"
          geometry={nodes.Male_Bushy_4.geometry}
          material={materials.Std_Skin_Arm}
          skeleton={nodes.Male_Bushy_4.skeleton}
          morphTargetDictionary={nodes.Male_Bushy_4.morphTargetDictionary}
          morphTargetInfluences={nodes.Male_Bushy_4.morphTargetInfluences}
        />
        <skinnedMesh
          name="Male_Bushy_5"
          geometry={nodes.Male_Bushy_5.geometry}
          material={materials.Std_Skin_Leg}
          skeleton={nodes.Male_Bushy_5.skeleton}
          morphTargetDictionary={nodes.Male_Bushy_5.morphTargetDictionary}
          morphTargetInfluences={nodes.Male_Bushy_5.morphTargetInfluences}
        />
        <skinnedMesh
          name="Male_Bushy_6"
          geometry={nodes.Male_Bushy_6.geometry}
          material={materials.Std_Nails}
          skeleton={nodes.Male_Bushy_6.skeleton}
          morphTargetDictionary={nodes.Male_Bushy_6.morphTargetDictionary}
          morphTargetInfluences={nodes.Male_Bushy_6.morphTargetInfluences}
        />
        <skinnedMesh
          name="Male_Bushy_7"
          geometry={nodes.Male_Bushy_7.geometry}
          material={materials.Std_Eyelash}
          skeleton={nodes.Male_Bushy_7.skeleton}
          morphTargetDictionary={nodes.Male_Bushy_7.morphTargetDictionary}
          morphTargetInfluences={nodes.Male_Bushy_7.morphTargetInfluences}
        />
        <skinnedMesh
          name="Male_Bushy_8"
          geometry={nodes.Male_Bushy_8.geometry}
          material={materials.Std_Tearline_R}
          skeleton={nodes.Male_Bushy_8.skeleton}
          morphTargetDictionary={nodes.Male_Bushy_8.morphTargetDictionary}
          morphTargetInfluences={nodes.Male_Bushy_8.morphTargetInfluences}
        />
        <skinnedMesh
          name="Male_Bushy_9"
          geometry={nodes.Male_Bushy_9.geometry}
          material={materials.Std_Tearline_L}
          skeleton={nodes.Male_Bushy_9.skeleton}
          morphTargetDictionary={nodes.Male_Bushy_9.morphTargetDictionary}
          morphTargetInfluences={nodes.Male_Bushy_9.morphTargetInfluences}
        />
        <skinnedMesh
          name="Male_Bushy_10"
          geometry={nodes.Male_Bushy_10.geometry}
          material={materials.Std_Upper_Teeth}
          skeleton={nodes.Male_Bushy_10.skeleton}
          morphTargetDictionary={nodes.Male_Bushy_10.morphTargetDictionary}
          morphTargetInfluences={nodes.Male_Bushy_10.morphTargetInfluences}
        />
        <skinnedMesh
          name="Male_Bushy_11"
          geometry={nodes.Male_Bushy_11.geometry}
          material={materials.Std_Lower_Teeth}
          skeleton={nodes.Male_Bushy_11.skeleton}
          morphTargetDictionary={nodes.Male_Bushy_11.morphTargetDictionary}
          morphTargetInfluences={nodes.Male_Bushy_11.morphTargetInfluences}
        />
        <skinnedMesh
          name="Male_Bushy_12"
          geometry={nodes.Male_Bushy_12.geometry}
          material={materials.Std_Eye_Occlusion_R}
          skeleton={nodes.Male_Bushy_12.skeleton}
          morphTargetDictionary={nodes.Male_Bushy_12.morphTargetDictionary}
          morphTargetInfluences={nodes.Male_Bushy_12.morphTargetInfluences}
        />
        <skinnedMesh
          name="Male_Bushy_13"
          geometry={nodes.Male_Bushy_13.geometry}
          material={materials.Std_Eye_Occlusion_L}
          skeleton={nodes.Male_Bushy_13.skeleton}
          morphTargetDictionary={nodes.Male_Bushy_13.morphTargetDictionary}
          morphTargetInfluences={nodes.Male_Bushy_13.morphTargetInfluences}
        />
        <skinnedMesh
          name="Male_Bushy_14"
          geometry={nodes.Male_Bushy_14.geometry}
          material={materials.Std_Tongue}
          skeleton={nodes.Male_Bushy_14.skeleton}
          morphTargetDictionary={nodes.Male_Bushy_14.morphTargetDictionary}
          morphTargetInfluences={nodes.Male_Bushy_14.morphTargetInfluences}
        />
        <skinnedMesh
          name="Male_Bushy_15"
          geometry={nodes.Male_Bushy_15.geometry}
          material={materials.Std_Eye_R}
          skeleton={nodes.Male_Bushy_15.skeleton}
          morphTargetDictionary={nodes.Male_Bushy_15.morphTargetDictionary}
          morphTargetInfluences={nodes.Male_Bushy_15.morphTargetInfluences}
        />
        <skinnedMesh
          name="Male_Bushy_16"
          geometry={nodes.Male_Bushy_16.geometry}
          material={materials.Std_Cornea_R}
          skeleton={nodes.Male_Bushy_16.skeleton}
          morphTargetDictionary={nodes.Male_Bushy_16.morphTargetDictionary}
          morphTargetInfluences={nodes.Male_Bushy_16.morphTargetInfluences}
        />
        <skinnedMesh
          name="Male_Bushy_17"
          geometry={nodes.Male_Bushy_17.geometry}
          material={materials.Std_Eye_L}
          skeleton={nodes.Male_Bushy_17.skeleton}
          morphTargetDictionary={nodes.Male_Bushy_17.morphTargetDictionary}
          morphTargetInfluences={nodes.Male_Bushy_17.morphTargetInfluences}
        />
        <skinnedMesh
          name="Male_Bushy_18"
          geometry={nodes.Male_Bushy_18.geometry}
          material={materials.Std_Cornea_L}
          skeleton={nodes.Male_Bushy_18.skeleton}
          morphTargetDictionary={nodes.Male_Bushy_18.morphTargetDictionary}
          morphTargetInfluences={nodes.Male_Bushy_18.morphTargetInfluences}
        />
      </group>
      <group scale={0.01}>
        <primitive object={nodes.CC_Base_BoneRoot_1} />
        <skinnedMesh
          name="Side_part_wavy_1"
          geometry={nodes.Side_part_wavy_1.geometry}
          material={materials.Scalp_Transparency}
          skeleton={nodes.Side_part_wavy_1.skeleton}
          morphTargetDictionary={nodes.Side_part_wavy_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Side_part_wavy_1.morphTargetInfluences}
        />
        <skinnedMesh
          name="Side_part_wavy_2"
          geometry={nodes.Side_part_wavy_2.geometry}
          material={materials.Hair_Transparency}
          skeleton={nodes.Side_part_wavy_2.skeleton}
          morphTargetDictionary={nodes.Side_part_wavy_2.morphTargetDictionary}
          morphTargetInfluences={nodes.Side_part_wavy_2.morphTargetInfluences}
        />
      </group>
      <PerspectiveCamera
        makeDefault={false}
        far={999.99}
        near={0}
        fov={14.426}
        position={[-0.098, 1.853, 5.516]}
        rotation={[0.037, -0.004, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lighting_Setup_Generator.geometry}
        material={nodes.Lighting_Setup_Generator.material}
      />
      <mesh
        geometry={nodes.Boots.geometry}
        material={materials['Boots.001']}
        scale={0.01}
      />
      <group scale={0.01}>
        <mesh
          geometry={nodes.Layered_sweater_1.geometry}
          material={materials.Layered_sweater}
        />
        <mesh
          geometry={nodes.Layered_sweater_2.geometry}
          material={materials['Material.001']}
        />
      </group>
      <mesh
        geometry={nodes.Slim_Jeans.geometry}
        material={materials['Slim_Jeans.001']}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload('/model2/Daven_v3.2.gltf');
